# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Do_oD
brief-intro: Road to Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://owner0220.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
github_username:  owner0220
email: test@gmail.com
linkedIn_username: 
dribbble_username:

description_footer: Do your best & Connecting the dots.

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #bloging
disqus_shortname: 

# statistic analysis 统计代码
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 
google_analytics_id:  # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
